name: cached_network_image_platform_interface
description: Platform interface for CachedNetworkImage
version: 4.0.0
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: git@github.com:11wizards/flutter_cache_manager.git
      ref: c742f98a0ff333bc5a0166f9f2f3f3e365eda8c6
      path: flutter_cache_manager

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
